# Generated by Django 5.1.1 on 2024-09-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
